FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ARG USERNAME=tester
ARG USERPASS=tester
RUN useradd -m -s /bin/bash "$USERNAME" \
    && echo "$USERNAME:$USERPASS" | chpasswd \
    && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/"$USERNAME" \
    && chmod 0440 /etc/sudoers.d/"$USERNAME"

USER $USERNAME
WORKDIR /home/$USERNAME/ubuntu-setup

COPY --chown=$USERNAME:$USERNAME . .

CMD ["/bin/bash"]
